# Generated by Django 3.0.7 on 2021-11-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211124_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='passangers',
            new_name='passengers',
        ),
    ]
